alphagov/govuk_app_config

README.md

Improve readme for automatic error reporting

---

README.md
lib/govuk_app_config.rb
lib/govuk_app_config/govuk_healthcheck.rb
lib/govuk_app_config/govuk_healthcheck/active_record.rb
lib/govuk_app_config/govuk_healthcheck/checkup.rb
lib/govuk_app_config/govuk_healthcheck/sidekiq_redis.rb
lib/govuk_app_config/govuk_logging.rb
spec/lib/govuk_healthcheck/active_record_spec.rb
spec/lib/govuk_healthcheck/checkup_spec.rb
spec/lib/govuk_healthcheck/shared_interface.rb
spec/lib/govuk_healthcheck/sidekiq_redis_spec.rb

This is a port of alphagov/govuk_healthcheck@db03b4d

Add healthcheck support

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Releases the new healthcheck functionality https://github.com/alphagov/govuk_app_config/pull/38

Release version 1.5.0

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Version 1.5.1

---

CHANGELOG.md
lib/govuk_app_config/version.rb

This includes some improvements to the default logging configuration.

Release version 1.13.0

---

CHANGELOG.md
lib/govuk_app_config/version.rb

[Trello card](https://trello.com/c/XUgnpLbM/119-action-item-fix-unicorn-worker-timeout)

Release 1.15.0

---

CHANGELOG.md
lib/govuk_app_config/version.rb

https://trello.com/c/j7mUrNuO/883-fix-csp-breaking-apps-in-development-environment

Bump version to 1.17.0

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Includes:
* Fix CSP in development
* Add `youtube-nocookie.com` to consent security policy

Version 1.20.0

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Version bump.
Slight edit to the past CHANGELOG - I went back in time to to make it clearer the differences between #133 and #130.

Bump to v2.0.3

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Trello card: https://trello.com/c/Ik7ulDXQ/1768-3-upgrade-frontend-to-rails-6

Bump to version 2.1.0

---

CHANGELOG.md

Visual Studio Code complained of unusual whitespace and offered
to remove it.

Remove strange whitespace

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Also adds a couple of missing links to the changelog.
Arises from #162.

Bump to 2.4.1

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Releasing the work done in #165.

Bump to 2.5.1

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Bump version to 2.7.1

---

lib/govuk_app_config/govuk_error.rb
lib/govuk_app_config/version.rb
spec/lib/govuk_error_spec.rb

https://trello.com/c/guK81BGF/2239-3-send-govukappconfig-version-with-errors

Add govuk_app_config version to every sentry call

---

CHANGELOG.md
govuk_app_config.gemspec
lib/govuk_app_config/version.rb

Also adds some missing information from previous releases.

Bump to 2.8.1

---

CHANGELOG.md
lib/govuk_app_config/version.rb

This release will add the new Redis healthcheck

Bump gem version to 2.8.3

---

CHANGELOG.md
lib/govuk_app_config/version.rb

This will release our custom i18n plural rules

Bump gem version to 2.9.0

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Trello: https://trello.com/c/8qzKKfNp/2588-release-new-major-version-for-govukappconfig-2

Release 4.0.0

---

CHANGELOG.md
lib/govuk_app_config/govuk_i18n.rb
lib/govuk_app_config/version.rb

Arising from https://trello.com/c/pPw5e9me/2828-apply-locale-file-validation-to-whitehall generalising code in alphagov/whitehall#6415

Add pluralisation rules for Azerbaijani, Persian, Georgian, and Turkish

---

CHANGELOG.md
govuk_app_config.gemspec
lib/govuk_app_config.rb
lib/govuk_app_config/govuk_prometheus_exporter.rb
lib/govuk_app_config/version.rb

This is a new module to allow for exporting prometheus metrics.

Add GovukPrometheusExporter module

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Includes:
- Update HMPO webchat address in security policy (#225)

Release v4.4.2

---

CHANGELOG.md
lib/govuk_app_config/govuk_prometheus_exporter.rb
lib/govuk_app_config/version.rb

Changed server bind address to 0.0.0.0 from localhost to allow for connections from outside of container

Prometheus exporter server update

---

CHANGELOG.md
lib/govuk_app_config/version.rb

https://github.com/alphagov/govuk_app_config/pull/248 merged but didn't release a new version, sorry, friday afternoon!

Bump version number

---

CHANGELOG.md
lib/govuk_app_config/version.rb

This will include #255 where Prometheus Sidekiq monitoring is
added.

Release version 4.7.0 of the Gem

---

CHANGELOG.md

Add release notes for v4.7.1.

---

CHANGELOG.md
lib/govuk_app_config/version.rb

This has various related to the Content Security Policy.

Release 4.12.0

---

lib/govuk_app_config/version.rb

This will allow us to configure puma timeouts

Release version 6.0.1

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Includes: 
- https://github.com/alphagov/govuk_app_config/pull/294

Release version 7.2.1

---

.github/workflows/ci.yml

This utilises the guidance introduced in: https://github.com/alphagov/govuk-developer-docs/pull/3961

Follow dev doc guidance on when GitHub Actions should run

---

CHANGELOG.md
lib/govuk_app_config/version.rb

Adding URLs for single cookie consent API.

Release v9.9.2

---

.gitignore
.govuk_dependabot_merger.yml
govuk_app_config.gemspec
spec/spec_helper.rb

- Adds code coverage checker
- Upgrades to govuk-dependabot-merger V2
- Enables auto-merge of external dependencies
Trello: https://trello.com/c/iC9shJG4/3479-roll-out-govuk-dependabot-merger-v2-across-select-repositories

Upgrade to govuk-dependabot-merger v2

---

.github/workflows/actionlint.yml
CHANGELOG.md
lib/govuk_app_config/version.rb

Bulk Update: Addresses govuk-infrastructure#1361
https://github.com/alphagov/govuk-infrastructure/issues/1361

Add Actionlint Checks

---

CHANGELOG.md
lib/govuk_app_config/govuk_i18n/ky.yml
lib/govuk_app_config/version.rb

⚠️ Make sure you [release a new version of this gem](https://github.com/alphagov/govuk_app_config/pull/356/files) after merging your changes. ⚠️
trello card: https://trello.com/c/165Wyl6E/3514-import-kyrgyz-translations-to-our-frontend-applications-fcdo-waiting-for-gem-translations

Add kyrgyz rails translations
