alphagov/govuk_app_config

- CHANGELOG.md
- lib/govuk_app_config/govuk_statsd.rb
We now delegate the methods to `client`. This means we don't have to use `GovukStatsd.client.time`, but just use `GovukStatsd.time`.
> Add `time` and `gauge` to `GovukStatsd`

- Rakefile
At the moment, running `rake spec` does not actually run the unit tests.
This change creates the `spec` task, so that it is run correctly by
the default Rake task.
> Fix `rake spec` task

- CHANGELOG.md
- README.md
- lib/govuk_app_config/configure.rb
- lib/govuk_app_config/govuk_error.rb
This allows us to configure Raven without actually mentioning Raven in the code. Inspired by https://github.com/alphagov/govuk_app_config/pull/5 and [this comment](https://github.com/alphagov/content-performance-manager/pull/353/files/21e8ebfb275857387339625b68ba091fa1047c34#r140194431).
cc @alecgibson
> Add GovukError.configure

- CHANGELOG.md
- README.md
- govuk_app_config.gemspec
All GOV.UK apps use unicorn as the web server, but we're using a wild variety of versions:
Name | Version
-- | --
asset-manager | 5.0.1
authenticating-proxy | 4.9.0
bouncer | 5.0.1
calculators | 5.0.1
calendars | 5.3.0
collections | 4.9.0
collections-publisher | 5.3.0
contacts-admin | 5.1.0
content-performance-manager | 5.3.0
content-store | 4.8.2
content-tagger | 5.0.1
design-principles | 4.3.1
email-alert-api | 5.3.0
email-alert-frontend | 5.3.0
feedback | 4.9.0
finder-frontend | 4.8.3
frontend | 4.9.0
government-frontend | 4.8.0
hmrc-manuals-api | 4.8.3
imminence | 4.3.1
info-frontend | 4.8.3
licence-finder | 5.1.0
link-checker-api | 5.3.0
local-links-manager | 4.9.0
manuals-frontend | 4.8.2
manuals-publisher | 4.8.2
maslow | 5.3.0
policy-publisher | 5.3.0
publisher | 5.3.0 …
> Add Unicorn as a dependency

- govuk_app_config.gemspec
2.7.0 was yanked. 2.7.1 fixes the issues (https://github.com/getsentry/raven-ruby/commit/fdb16bb16d5139f6be12dd85835a5e981e0854c9).
Supersedes #13.
> Bump sentry-raven to 2.7.1

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
This happens when a client makes an invalid request to the application. There's no need for us to act on these errors.
In terms of https://github.com/alphagov/govuk-rfcs/pull/87, this is a [Bad request error](https://github.com/alphagov/govuk-rfcs/blob/errors/rfc-087-dealing-with-errors.md#bad-request-errors) and should not be sent to Sentry. In future versions of the Sentry client it might even be ignored by default: https://github.com/getsentry/raven-ruby/pull/769.
Trello: https://trello.com/c/wX66HhtR
Examples:
- https://sentry.io/govuk/app-calculators/issues/354179330
- https://sentry.io/govuk/app-government-frontend/issues/364427882
> Ignore `ActionController::BadRequest`

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_logging.rb
- lib/govuk_app_config/railtie.rb
GOV.UK applications use logstasher to output logs as JSON so they can be shipped to Kibana. 
Over the years copy-and-changing has led to a complete circus of different logging configurations. 
Here's a list of applications and versions:
Application  | Logstasher version
-- | --
asset-manager | 0.4.8
authenticating-proxy | 0.6.5
calculators | 0.6.5
calendars | 1.2.1
collections | 0.6.2
collections-publisher | 1.2.1
content-performance-manager | 1.2.1
content-store | 0.5.0
content-tagger | 1.2.1
design-principles | 0.4.8
email-alert-api | 1.2.1
feedback | 0.6.2
finder-frontend | 0.4.9
frontend | 1.1.0
government-frontend | 0.6.1
hmrc-manuals-api | 0.5.3
imminence | 0.4.8
info-frontend | 0.6.0
licence-finder | 0.6.5
link-checker-api | 0.9.0
local-links-manager | 0.6.2
manuals-frontend | …
> Configure logging using this gem

- CHANGELOG.md
- lib/govuk_app_config/version.rb
First full release because it now does quite a lot of things, and is used in production by all the apps.
> Release version 1.0.0

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_statsd.rb
This introduces statsd methods which were not delegated before and updates the documentation to have a closer reflection to what the statsd env var actually is.
> Statsd tweaks

- govuk_app_config.gemspec
Some apps (e.g. search-admin) are already using the latest version of unicorn.
Release notes: https://github.com/defunkt/unicorn/releases/tag/v5.4.0
> Upgrade unicorn dependency

- lib/govuk_app_config/govuk_logging.rb
All our applications in production should use `INFO` log level. The
default for new `Logger` instances is `DEBUG`. This is causing
applications to log multiple gig in production.
> Use INFO log level for unstructured logging

- CHANGELOG.md
- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_unicorn.rb
This is to provide a shared configuration for unicorn. Currently GOV.UK
apps rely on this notification to be provided by puppet through
[/etc/govuk/unicorn.rb][1] being created on each host. Then at the point
of running an app there is a [check][2] for whether a `config/unicorn.rb`
exists otherwise the puppet file will be used.
That approach has a few downsides:
1) There is code injected into the app at runtime which is not run in
other environments, notably test ones
2) There is a coupling between apps and govuk-puppet which is
unnecessary
3) It's something of an anomaly in govuk_app_config to provide a tool
(unicorn) but not it's configuration.
This approach resolves those but does have it's own downside that there
does not seem to be a way to configure unicorn automatically so apps are …
> Unicorn config

- CHANGELOG.md
We missed some of the other bits of logstasher config that 
should be removed from an app when we upgrade to 1.0.0+
and let govuk_app_config handle configuring logstasher.
> Add extra details to How to upgrade for v1.0.0

- lib/govuk_app_config/govuk_statsd.rb
Engage with gauging language.
This should fix some stats reporting in the content-store: https://sentry.io/govuk/app-content-store/issues/450067775/
> Fix spelling of "gauge" in statsd

- CHANGELOG.md
- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_logging.rb
This PR is to try address a prickly issue affecting Unicorn and Logstasher which is causing our log files to be sent to actual STDOUT rather than going into the Unicorn STDOUT log file.
To reduce risk of similar issues and streamline things I'm suggesting that the unicorn config is included by requiring the exact file. This seemed like a bit of annoying change to have as a major version breaking change so I've deprecated this so it can be handled when this Gem reaches 2.0.
Before this change:
```
➜  email-alert-api git:(logging-battle) ✗ bundle exec unicorn -c ./config/unicorn.rb
I, [2018-02-27T22:40:43.490058 #43693]  INFO -- sentry: ** [Raven] Raven 2.7.2 configured not to capture errors: DSN not set
{"method":"GET","path":"/","format":"json","controller":"welcome","action":"index","stat …
```
> STDOUT woes

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
As per [GOV.UK RFC 87][rfc87], we should only log actionable errors that aren’t
intermittent. We should specify these rules in this gem.
This relies on version [52.1.0] of `gds-api-adapters`, however it’s safe to
use on older versions as we only do string matching for the exception.
[rfc87]: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-087-dealing-with-errors.md
[52.1.0]: https://github.com/alphagov/gds-api-adapters/pull/813
> Count intermittent API errors instead of logging to Sentry

- lib/govuk_app_config/configure.rb
If an API error occurs while processing a template, it’ll actually end
up wrapped in an `ActionView::Template::Error`. If this is the case, we
need to check the `original_exception` class instead.
> Check the original exception if it exists for intermittent failure

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
We're seeing these a lot in Whitehall for some reason, but there's no need to report the error as Rails handles it approriately.
> Ignore ActionController::UnknownHttpMethod errors

- lib/govuk_app_config/configure.rb
These errors are unactionable so shouldn't be reported:
https://docs.publishing.service.gov.uk/manual/errors.html#ip-spoof-errors
> Don't report ActionDispatch::RemoteIp::IpSpoofAttackError

- lib/govuk_app_config/configure.rb
Based on the discussion in https://github.com/alphagov/whitehall/pull/3751 we can add this to the list of excluded exceptions.
> Add ActionController::ParameterMissing to the excluded exceptions

- CHANGELOG.md
- lib/govuk_app_config/govuk_healthcheck.rb
- spec/lib/govuk_healthcheck_spec.rb
Since we're returning JSON on this endpoint we should set the `Content-Type` header.
> Make health check endpoint set Content-Type header

- CHANGELOG.md
- lib/govuk_app_config/govuk_healthcheck/checkup.rb
It makes more sense for them to be symbols as they should be immutable. This also provides better compatibility with the existing health check systems in various apps.
> Make the health check statuses symbols

- CHANGELOG.md
- README.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_healthcheck/active_record.rb
- lib/govuk_app_config/govuk_healthcheck/checkup.rb
- lib/govuk_app_config/govuk_healthcheck/sidekiq_redis.rb
- spec/lib/govuk_error_spec.rb
- spec/lib/govuk_healthcheck/active_record_spec.rb
- spec/lib/govuk_healthcheck/checkup_spec.rb
- spec/lib/govuk_healthcheck/shared_interface.rb
- spec/lib/govuk_healthcheck/sidekiq_redis_spec.rb
While adding support for more advanced health checks in email-alert-api we switched over to using this framework provided by govuk_app_config.
One thing we've discovered is that by having health checks be a long running class instance, we can't cache any queries and a single health check could end up running the same query three times: for the status, details and message.
We could change the way health checks work and make them more complicated in email-alert-api, but I suspect this will be a problem which affects many other apps so I decided we should change the behaviour of govuk_app_config to expect health checks to be classes, which can then be instanced at the time of the request. This also follows the same behaviour of email-alert-api before it switched over to using this interface. …
> Expect health checks to be classes not instances

- CHANGELOG.md
- lib/govuk_app_config/version.rb
The change is technically a breaking change, but I consider the health check system still in development/prototype and we may have some more future breaking changes and the number will climb high very quickly. It's currently only being used by email-alert-api, and the interface for apps which have no custom checks won't even change after this.
> Bump version 1.6.0

- CHANGELOG.md
- README.md
- docs/healthchecks.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_healthcheck.rb
- lib/govuk_app_config/govuk_healthcheck/checkup.rb
- lib/govuk_app_config/govuk_healthcheck/sidekiq_queue_check.rb
- lib/govuk_app_config/govuk_healthcheck/sidekiq_queue_latency_check.rb
- lib/govuk_app_config/govuk_healthcheck/sidekiq_queue_size_check.rb
- lib/govuk_app_config/govuk_healthcheck/sidekiq_retry_size_check.rb
- lib/govuk_app_config/govuk_healthcheck/threshold_check.rb
- spec/lib/govuk_healthcheck/checkup_spec.rb
- spec/lib/govuk_healthcheck/shared_interface.rb
- spec/lib/govuk_healthcheck/sidekiq_queue_check_spec.rb
- spec/lib/govuk_healthcheck/sidekiq_queue_latency_check_spec.rb
- spec/lib/govuk_healthcheck/sidekiq_queue_size_check_spec.rb
- spec/lib/govuk_healthcheck/sidekiq_retry_size_check_spec.rb
- spec/lib/govuk_healthcheck/threshold_check_spec.rb
- spec/spec_helper.rb
This PR adds a few useful health check base classes which can be used as the basis for more specific application checks. It also improves the documentation and adds the ability to disable/enable health checks during the course of an applications lifetime.
The base classes added are:
- Threshold check which compares a value (or a set of values) with a warning and a critical threshold
- Sidekiq queue size check which compares the size of individual queues with thresholds
- Sidekiq queue latency check which compares the latency of individual queues with thresholds
- Generic Sidekiq queue check which makes it easy to have a threshold check which gets applied on each queue individually
[Trello Card](https://trello.com/c/iuPQ6P88/318-add-common-parameterised-healthcheck-classes)
> Health check convenience classes

- CHANGELOG.md
- lib/govuk_app_config/govuk_healthcheck/checkup.rb
- spec/lib/govuk_healthcheck/checkup_spec.rb
This will set the status of the check to critical and include the exception in the message.
[Trello Card](https://trello.com/c/iuPQ6P88/318-add-common-parameterised-healthcheck-classes)
> Handle a health check which raises an exception

- lib/govuk_app_config/configure.rb
This is useful to have logged in production, but is distracting
everywhere else.
> Stop saying errors are not going to be captured in dev

- CHANGELOG.md
- lib/govuk_app_config/govuk_xray.rb
If there is a problem with the instrumentation, we want to know that -
but we don't want the behaviour of the app to be affected.
The current behaviour is causing e2e test failures in frontend and whitehall.
---
[Trello card](https://trello.com/c/PFXPhBxO/451-install-default-x-ray-gem-for-rails-in-all-our-apps-mandatory-%F0%9F%8D%90)
> Log, but do not throw, on missing XRay request context

- CHANGELOG.md
- lib/govuk_app_config/govuk_xray.rb
**I'll open an issue on aws-xray-sdk if other people agree with my conclusion.**
---
Since applying the last round of govuk_app_config upgrades, asset-manager and publishing-api have been using far more memory:
The memory shoots up as soon as the app is deployed, so I believe this is an overhead imposed at initialisation-time, rather than some sort of leak which manifests when requests are made.
After doing some debugging (commenting out lines of code and crossing my fingers), I narrowed this down to having X-Ray patch the `aws_sdk` gem.  If that gem is patched, the problem occurs; if it is not, even if `net_http` is patched, the memory usage seems much closer to before.
It's a shame to lose tracking for stuff which goes through `aws_sdk`, but that's only a small amount of stuff (asset …
> Check for XRAY_PATCH_AWS_SDK env var, and do not patch aws_sdk if unset

- CHANGELOG.md
- lib/govuk_app_config/railtie.rb
- spec/lib/railtie_spec.rb
The setting up of dummy classes for the test code is a bit unpleasant.
> Allow disabling X-Ray railtie through env var

- docs/healthchecks.md
- lib/govuk_app_config/govuk_healthcheck/checkup.rb
- spec/lib/govuk_healthcheck/checkup_spec.rb
Adds support for adding parametrized classes for the health check chain:
```ruby
get "/healthcheck", to: GovukHealthcheck.rack_response(
GovukHealthcheck::SidekiqRedis,
GovukHealthcheck::ActiveRecord,
GovukHealthcheck::InitializedCheck.new(:param),
)
```
Enable applications to reuse the same Check without being forced
to use inheritance or other mechanisms.
This is introduced in https://github.com/alphagov/content-performance-manager/pull/1131/commits/73aec09c289f785c06040845662c61a7f4d163e1, and is part of PR https://github.com/alphagov/content-performance-manager/pull/1131. We aim to reuse the same check for multiple metrics.
> Enable initialized health check classes

- lib/govuk_app_config/govuk_healthcheck/active_record.rb
- spec/lib/govuk_healthcheck/active_record_spec.rb
Previously the AR healthcheck used to call '.connected?' and return a
status based on the boolean return value. But if the app is not being
used much, then the connection pool may be empty as all the idle
connections will have been removed. This changes the approach to
explicitly requests a connection if it doesn't already exist, which
means we should have less false negatives for low-traffic apps.
> Make ActiveRecord healthcheck less flakey

- CHANGELOG.md
- lib/govuk_app_config/govuk_logging.rb
This logger is now used by GDS API Adapters by default, but it
includes the default metadata, so the resulting output isn't valid
JSON.
Therefore, change the formatter so that it's just the message that's
logged.
> Remove formatting from the logstasher logger

- CHANGELOG.md
- lib/govuk_app_config/version.rb
This includes one change, to remove formating from the Logstasher
logger, used by default for the GDS API Adapters logging.
> Release version 1.13.1

- CHANGELOG.md
- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_content_security_policy.rb
This commit moves support for content security policy headers from government-frontend to this gem to allow all frontend apps to use it.
> Add support for content security policy

- lib/govuk_app_config/govuk_unicorn.rb
Unicorn has a default timeout of 60s, nginx has a different timeout.
We should make the unicorn timeout configurable so that it can match
nginx.
Unicorn recommends some additional nginx configuration if changing its
timeout:
> For running Unicorn behind nginx, it is recommended to set
> “fail_timeout=0” for in your nginx configuration like this to have
> nginx always retry backends that may have had workers SIGKILL-ed due
> to timeouts.
---
[Trello card](https://trello.com/c/XUgnpLbM/119-action-item-fix-unicorn-worker-timeout)
> Allow configuring the unicorn timeout

- CHANGELOG.md
- lib/govuk_app_config/govuk_unicorn.rb
https://www.rubydoc.info/gems/unicorn/Unicorn/Configurator#timeout-instance_method
> Unicorn config.timeout is a method, not an lvalue

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
Smokey is currently failing because pages in Licensify include a doubleclick tracking image. We need to include this domain to our content security policy to make sure that we don't block access to that domain.
```
Feature: Licensing
Tests for the Licensify app.
@normal @notintegration
Scenario: Check licensing app is present    # features/licensing.feature:5
Given I am testing "licensing" internally # features/step_definitions/smokey_steps.rb:11
And I am testing through the full stack   # features/step_definitions/smokey_steps.rb:19
And I force a varnish cache miss          # features/step_definitions/smokey_steps.rb:26
Then I should be able to visit:           # features/step_definitions/smokey_steps.rb:120
| Path                                                       |
| …
```
> Add stats.g.doubleclick.net as a Google Analytics domain

- CHANGELOG.md
- lib/govuk_app_config/govuk_healthcheck/sidekiq_redis.rb
- spec/lib/govuk_healthcheck/sidekiq_redis_spec.rb
Redis raises a connection error if it's not available so this will catch those. I used StandardError so that it will be raised regardless if `Redis` exists in the application this is used.
> Return critical status for Redis connection errors

- CHANGELOG.md
- lib/govuk_app_config/govuk_xray.rb
This will remove persistent logging of `ERROR -- : can not find the current context.` from our logs.
This is from the aws-xray-sdk-ruby gem. Changing the log level in this way seems to have no side effects.
See: https://github.com/aws/aws-xray-sdk-ruby/blob/5134f203a0a0c7681e137aa6045ad64fc645c8fe/lib/aws-xray-sdk/context/default_context.rb#L62
> Change context_missing error level

- CHANGELOG.md
- lib/govuk_app_config/govuk_xray.rb
- lib/govuk_app_config/version.rb
This change used a config option for Xray that silenced errors:
https://github.com/aws/aws-xray-sdk-ruby/pull/18 however this option has
not been released in the most recent version of the gem 0.11.1 and
besides that this project is tied to use 0.10 of that gem.
> Revert the Xray IGNORE_ERROR change

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
https://trello.com/c/j7mUrNuO/883-fix-csp-breaking-apps-in-development-environment
Previously our Content Security Policy (CSP) disallowed content from
our own apps when run in development with the 'dev.gov.uk' domain. Our
frontend apps rely on externals assets (e.g. from static.dev.gov.uk)
and these are not allowed under the current policy.
We also hardcode some assets, such as 'placeholder.png' to be served
from the production assets domain. This means that we should allow for
both 'dev.gov.uk' and 'publishing.service.gov.uk' in development. But we
should avoid implicitly trusting 'dev.gov.uk' outside of development.
This also removes 'localhost' from all policies, as it should normally
be covered by 'self', which applies to content requested from the same
domain and port. It would …
> Tweak our CSP to work with 'dev.gov.uk'

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_content_security_policy.rb
- spec/lib/govuk_content_security_policy_spec.rb
This is built off https://github.com/alphagov/govuk_app_config/pull/90 with the expectation that will be merged first.
This refactors the CSP to use the Rails DSL, this is backwards
compatible with the previous implementation. This refactor provides a few
benefits:
- no longer needs to set up the actual policy, just configuration
needed;
- apps can add/remove things to the policy if needed;
- the nonce generator allows setting a nonce on inline javascript tags
I've reduced the amount of comments in this file for brevity. A lot of
the example URLs felt unnecessary for the source code and felt more like they
belonged in a commit message.
> Use Rails DSL for CSP

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
Argh embarrassing fix alert.
Turns out the report_uri isn't set with an equals as I'd interpreted it and this didn't get caught in tests as it was behind a `Rails.env.production?` conditional. https://github.com/alphagov/govuk-puppet/pull/9187 should allow us to remove those conditionals so this can be tested. 
I've tested this out with a government-frontend build: https://deploy.integration.publishing.service.gov.uk/job/Deploy_App/9640/console which passes.
And I've also deployed this to integration to check the CSP output matches.
Current government-frontend release (govuk_app_config 1.16.2)
```
Content-Security-Policy-Report-Only: default-src https 'self' *.publishing.service.gov.uk localhost; img-src data: 'self' *.publishing.service.gov.uk localhost www.google-analytics.com …
```
> Fix report_uri CSP DSL method

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- spec/lib/govuk_content_security_policy_spec.rb
This uses the 12-factor approach of using environment variables to
determine the configuration of the content security policy instead of
using Rails.env.production?
This has a few advantages:
- We can set different report_uri for different apps (the current one is
set up for frontend GOV.UK apps)
- These lines of codes are executed in test environments, which caused a
problem in 86f9a0e
- This breaks the assumption that Rails.env.production means this is
running in GOV.UK integration/staging/production which is useful as this
is used for running end-to-end tests and should be available if devs
wish to try out production optimisations.
Environment variables for these were introduced to Puppet in
https://github.com/alphagov/govuk-puppet/pull/9187 and were released to
production in …
> Set CSP production configuration via ENV vars

- CHANGELOG.md
- lib/govuk_app_config/version.rb
Use `GOVUK_CSP_REPORT_ONLY` and `GOVUK_CSP_REPORT_URI` environment
variables to configure content security policy.
I've flagged this a minor version as there is not any backwards
compatibility concerns for GOV.UK applications as puppet already has
these environment variables.
> Release version 1.19.0

- lib/govuk_app_config/govuk_content_security_policy.rb
Adds `youtube-nocookie.com` to the GOVUK Content Security Policy.
We are [updating the media player on GOV.UK to use the Youtube player](https://github.com/alphagov/govuk_publishing_components/pull/908) rather than Nomensa accessible player. This change involves using Youtube's Privacy Enhanced mode (youtube-nocookie.com). Our current security policy only allows `youtube.com`, so we need to add `youtube-nocookie.com`
> Add youtube-nocookie.com to CSP

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_content_security_policy.rb
Most frontend apps in development can be started with `--live`, which sets the `GOVUK_APP_DOMAIN` to `www.gov.uk` ([government-frontend for example](https://github.com/alphagov/government-frontend/blob/master/startup.sh)).
Should clear up the confusion in https://github.com/alphagov/govuk-developer-docs/pull/1845#discussion_r301455194.
> Fix CSP in development

- lib/govuk_app_config/configure.rb
We no longer use Airbrake anywhere on GOV.UK, so we don't need this check anymore.
> Remove Airbrake check

- lib/govuk_app_config/configure.rb
- spec/integration/configuring_spec.rb
This commit:
- Uses the new `before_send` for pre-send stats. Because we now track all error types, the key is renamed.
- Use `config.inspect_exception_causes_for_exclusion` for excluding exceptions
- Remove "errbit" error key, as it's no longer used.
Similar to https://github.com/alphagov/govuk_app_config/pull/70.
> Update error reporting code

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
The `config.before_send` function has to return the event to send:
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/client.rb#L24-L31
> Fix reporting errors cause an error

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
There is no such constant in gds-api-adapters as
GdsApi::HTTPIntermittent. Instead there are two different constants that
are prefixed with GdsApi::HTTPIntermittent:
GdsApi::HTTPIntermittentClientError and
GdsApi::HTTPIntermittentServerError. Thus errors are now being reported
that would previously been excluded.
Presumably this mistake was made as we were previously just checking the
prefix of the class name in [1].
I decided we should only exclude intermittent server errors as applications
should be informed if they are making a client error (the case where you
would get a HTTPIntermittentClientError would be for too many requests, 429).
[1]: https://github.com/alphagov/govuk_app_config/commit/3c46b628a899717e7aec40273cf920bf7ff1a7c1
> Fix incorrect error constant

- CHANGELOG.md
- lib/govuk_app_config/version.rb
* Fix GdsApi::HTTPIntermittentServer errors no longer being filtered from
exceptions sent to Sentry.
> Release version 1.20.2

- lib/govuk_app_config.rb
This ordering was causing a problem for govuk_publishing_components which prevented assets to be pre-compiled:
```
govuk_publishing_components git:(master) RAILS_ENV=production GOVUK_APP_DOMAIN=www.gov.uk GOVUK_WEBSITE_ROOT=https://www.gov.uk rake assets:precompile
rake aborted!
NameError: uninitialized constant GovukAppConfig::Railtie::GovukLogging
/Users/kevindew/govuk/govuk_publishing_components/spec/dummy/config/initializers/content_security_policy.rb:1:in `<top (required)>'
/Users/kevindew/govuk/govuk_publishing_components/spec/dummy/config/environment.rb:5:in `<top (required)>'
/Users/kevindew/govuk/govuk_publishing_components/Rakefile:18:in `block (2 levels) in <top (required)>'
```
This was due to the Railtie file executing it's initializer before the remaining files had been …
> GovukLogging is required before Railtie

- CHANGELOG.md
- lib/govuk_app_config/version.rb
* Reorder requires to resolve: "NameError: uninitialized constant
GovukAppConfig::Railtie::GovukLogging"
> Release 2.0.1

- lib/govuk_app_config/govuk_content_security_policy.rb
Have added an entry for the new HMRC webchat provider URL, sitting on the Nuance domain. 
This is to facilitate calling an availability API endpoint on the third-parties domain and not throwing CORS or CSP issues when the ajax request originates on gov.uk contact pages.
> Added script-src for Nuance/HMRC Webchat provider

- lib/govuk_app_config/govuk_content_security_policy.rb
Added in the base domains to access availability URLS in "connect-src"
Nuance - HMRC web chat provider: hmrc-uk.digital.nuance.com
klick2contact - HMPO web chat provider: gov.klick2contact.com
> Updated CSP to for new HMRC & HMPO provider

- docs/healthchecks.md
I recently did some work on a healthcheck endpoint and noticed that some apps were using the details method in their healthchecks to provide information that should be showing up in icinga. It took me quite a while to work out that it's the message method rather than details that icinga actually shows. This updates the docs to make it clear that the message method provides a string that can be seen in icinga.
> Include information re. icinga in message section of healthcheck doc

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
TL;DR: This stops exceptions rescued by rails from appearing in Sentry.
After upgrading `frontend` to rails 6, we started seeing this error:
`Mime::Type::InvalidMimeType "charset=utf-8" is not a valid MIME type`
Example here:
https://www.sentry.io/organizations/govuk/issues/1549200925/?end=2020-03-06T12%3A00%3A23&environment=staging&project=202225&query=is%3Aunresolved+url%3Ahttps%3A%2F%2Fwww-origin.staging.govuk.digital%2Freport-an-unregistered-trader-or-business&start=2020-03-05T16%3A07%3A23&utc=true
This is because, even though these errors are rescued by ActionDispatch,
they still reach Sentry. Here's the explanation from Sentry's docs:
> Rails catches exceptions in the ActionDispatch::ShowExceptions or
> ActionDispatch::DebugExceptions middlewares, depending on the
> environment. …
> Do not report exceptions rescued by rails

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
This reverts https://github.com/alphagov/govuk_app_config/pull/138
It turns out that this setting was more aggressive than we anticipated
and was actually preventing the reporting of any exception that Rails
handled. We had thought that this only prevented the reporting of
exceptions specially configured as Rails rescue responses.
It transpires that this stops the reporting of any exceptions that are
handled by ActionDispatch::ShowExceptions [1] which is effectively all
Rails exceptions as per raven-ruby [2].
[1]: https://github.com/rails/rails/blob/38ec8db3f7d3c79936cdaa0a136b26ee1c977f7d/actionpack/lib/action_dispatch/middleware/show_exceptions.rb
[2]: https://github.com/getsentry/raven-ruby/blob/d9d41784c3b5888295bf4b013416f132045b22d4/lib/raven/integrations/rails.rb#L51-L52
> Revert rails_report_rescued_exceptions = false

- CHANGELOG.md
- lib/govuk_app_config/version.rb
* Revert using Sentry option of rails_report_rescued_exceptions (https://github.com/alphagov/govuk_app_config/pull/140)
> Bump to version 2.1.1

- CHANGELOG.md
- lib/govuk_app_config/configure.rb
In updating the default Rails ones I failed to realise that some were
configured in ActionDispatch [1] and others were in ActiveRecord [2] so
the last iteration of this missed all of these.
[1]: https://github.com/rails/rails/blob/eed9f15ba87d4d4c9be48119e55e8ff17102c4a7/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L8-L24
[2]: https://github.com/rails/rails/blob/eed9f15ba87d4d4c9be48119e55e8ff17102c4a7/activerecord/lib/active_record/railtie.rb#L22-L27
> Exclude ActiveRecord rescue responses

- CHANGELOG.md
- lib/govuk_app_config/version.rb
Add missing ActiveRecord rescue_responses (https://github.com/alphagov/govuk_app_config/pull/142)
> Bump to 2.1.2

- lib/govuk_app_config/govuk_logging.rb
This was fixed in logstasher here: https://github.com/shadabahmed/logstasher/commit/bc9e6cfed51a9aea3f27610ee0bcf1d90db5da9b
They've maintained backwards compatibility but it is better if we use the correct parameter, just in
case configuration has shifted. It will also make it easier to look up the correct documentation.
Arises from https://trello.com/c/fX8U5tly/1911-5-fix-whitehall-stacktraces-in-kibana
> Fix spelling of `supressed` => `suppressed`

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_logging.rb
- lib/govuk_app_config/rails_ext/action_dispatch/debug_exceptions.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_logging_spec.rb
- spec/lib/rails_ext/action_dispatch/debug_exceptions_spec.rb
It's annoying having Rails log errors across multiple lines, as it makes
indexing them in logstash very difficult.
:warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey:
This PR involves monkey patching a small bit of rails
:warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey: :warning: :monkey:
The ActionDispatch::DebugExceptions middleware is the culprit that's logging
errors across multiple lines. Since it would be a bit of a nuisance to have to
replace this middleware entirely (it does other things too - like rendering
error pages in dev), it seems more "surgical" just to replace the `log_error`
method with one …
> Monkey patch log_error - format errors on one line

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
We are making requests to www.googletagmanager.com in govuk_publishing_components [1], and including JavaScript and CSS from www.gstatic.com in content-data-admin [2].  All were being blocked by the Content Security Policy, therefore adding these domains to the policy.
1: https://github.com/alphagov/govuk_publishing_components/blob/21e5808e03e7c97721cefe533b315753db7c5403/app/views/govuk_publishing_components/components/_google_tag_manager_script.html.erb#L16
2: https://github.com/alphagov/content-data-admin/blob/2bbf6cd4bbae29ec02107f4341d526f7707be6d6/app/views/layouts/application.html.erb#L2
> Add two missing Google domains to Content Security Policy

- CHANGELOG.md
- docs/healthchecks.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_healthcheck.rb
- lib/govuk_app_config/govuk_healthcheck/mongoid.rb
- lib/govuk_app_config/govuk_healthcheck/rails_cache.rb
- lib/govuk_app_config/rails_ext/action_dispatch/debug_exceptions.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_healthcheck/mongoid_spec.rb
- spec/lib/govuk_healthcheck/rails_cache_spec.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Please see the commits for more details.
> Add a couple of new healthchecks

- govuk_app_config.gemspec
In order to improve Sentry's grouping of errors, we want to make
use of the `backtrace_cleanup_callback` introduced in 3.1.0:
https://github.com/getsentry/sentry-ruby/pull/1011
`backtrace_cleanup_callback` automatically uses a
[customised version of Rails::BacktraceCleaner](https://github.com/getsentry/sentry-ruby/pull/1011/files#diff-c01d5cbc846720e47a4185cb501a55225247ec698aa169b0a2773ca9b65ae35dR4-R29)
if we don't specify our own. It means that for stack traces like:
`app/views/welcome/view_error.html.erb in _app_views_welcome_view_error_html_erb__2807287320172182514_65600 at line 1`
...these lines get normalised to:
`app/views/welcome/view_error.html.erb at line 1`
So if the same `ActionView::Template::Error` error happens twice,
it will now be grouped instead of erroneously treated …
> Bump 'sentry-raven' to 3.1.1 to improve grouping of errors

- lib/govuk_app_config/govuk_error/configuration.rb
- spec/govuk_error/configuration_spec.rb
We're seeing PG:UndefinedTable errors in Sentry, which we'd like
to ignore during the data sync. By default we're ignoring PG::Error
exceptions already, but this is a specific sub class of PG::Error
(and there are many more we envisage wanting to ignore). We
could list all of these subclasses in the
`data_sync_excluded_exceptions` array, but what we'd rather do
is describe the parent class and have any of its children
exceptions ignored.
`PG::Error === PG::UndefinedTable.new` is true, whereas
`"PG::Error" === PG::UndefinedTable.new.class` is false.
This commit makes the default `should_capture` behaviour dig
deeper into the exception, checking that the exception type
is classed as any one of the errors we've chosen to ignore.
From now on, any exceptions that are a subclass of `PG::Error` …
> Also ignore subclasses of `data_sync_excluded_exceptions`

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
[Explanation](https://stackoverflow.com/questions/60459709/where-is-simpledelegator-in-ruby-2-7).
TLDR:
> The Delegator and SimpleDelegator classes aren't core classes
> like Array or Mutex. They're part of the delegate standard
> library which needs to be loaded first: require 'delegate'.
> It happened to work in older Ruby versions as they came with an
> older RubyGems version by default. RubyGems is automatically
> loaded since Ruby 1.9 and until 3.1.0 that meant delegate was
> loaded indirectly. Updating RubyGems or running ruby with
> --disable=gems should cause the exact same issue with Ruby <=
> 2.6 too. irb also loads several standard libraries: delegate
> but also timeout and many more.
This is causing the [bouncer build to error](https://github.com/alphagov/bouncer/pull/273).
> Fix govuk_app_config in Ruby 2.7 environments by explicitly requiring the 'delegate' library

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/govuk_error/configure.rb
- lib/govuk_app_config/version.rb
- spec/govuk_error/configuration_spec.rb
We sometimes spin up temporary environments (e.g. 'test-pink-aws')
while developing applications. If there are errors in those apps,
we can accidentally send many thousands of errors to Sentry, which
can mean we hit rate limits on our other, production,
environments, as we have a single shared Sentry account.
This commit introduces a `active_sentry_environments` config
property, which is checked against the SENTRY_CURRENT_ENV ENV
variable. If an error occurs in an environment we care about,
it is reported to Sentry, otherwise it gets ignored.
There is prior art for this - in #160 we added a similar check,
such that if a particular error occurs during the nightly data
sync, it gets ignored. I've made sure this new functionality is
compatible with what's already been added.
Trello: …
> Ignore errors that occur in temporary environments

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configure.rb
- lib/govuk_app_config/version.rb
https://trello.com/c/qqGgd6mA/598-dev-pain-slimmer-causes-500-errors-for-transient-communication-errors-with-static
Related to: https://github.com/alphagov/slimmer/pull/257
> Ignore intermittent retrieval errors from Slimmer

- lib/govuk_app_config/govuk_error/govuk_data_sync.rb
Previously we used ".present?" to check for from/to attributes, but
these methods are only available in Rails app. This switches to using
standard library methods to ensure the code works in all our apps.
Example error:
Uncaught exception from consumer #<Bunny::Consumer:50260 @channel_id=1 @queue=email_unpublishing>
@consumer_tag=bunny-1606752847000-821140807868>: #<NoMethodError: undefined method `present?'
for 2020-11-30 22:00:00 +0000:Time> @ /data/vhost/email-alert-service/shared/bundle/ruby/2.7.0/
gems/govuk_app_config-2.7.0/lib/govuk_app_config/govuk_error/govuk_data_sync.rb:31:in `in_progress?'
> Fix using non-existent Rails method

- lib/govuk_app_config/govuk_error/configure.rb
We saw a [spike in errors](https://sentry.io/organizations/govuk/issues/2067287240/?project=202252) on
Staging between 1 and 2am (peak datasync time), resulting from Smart Answers requesting items from
the Content Store. These requests seem to correspond with the
[feature test in Smokey](https://github.com/alphagov/smokey/blob/e9b24251e5be5cc6bae5dc0fd8b2820c1d3efbb9/features/smartanswers.feature#L18).
Whilst we should probably consider the merits of continuing to run Smokey during a data sync, more
generally we know not to rely on Content Store during this period, as its DB gets dropped and repopulated
with production data. So `GdsApi::ContentStore::ItemNotFound` errors seem a good candidate for ignoring
during the data sync period.
> Add GdsApi::ContentStore::ItemNotFound to data_sync_excluded_exceptions

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_statsd.rb
This enables apps to specify both the host and protocol to use when sending metrics to Statsd.
This change is required for apps running in ECS, since Statsd won't run on localhost and [apps won't send messages to Statsd over UDP](https://github.com/aws/aws-app-mesh-roadmap/issues/57).
This should have no effect on apps currently running in EC2. The defaults `"localhost"` and `:udp` aren't required, since they duplicate [the defaults in the Statsd gem](https://github.com/reinh/statsd/blob/master/lib/statsd.rb#L294) - I've put them in for clarity.
This also temporarily drops in a new Statsd client. This gem (published by me) is my fork of our current client but with [this PR merged in](https://github.com/reinh/statsd/pull/77) - I'll switch the gem back once my PR is merged in.
> Permit apps to send messages to Statsd over TCP

- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_statsd.rb
This partially reverts https://github.com/alphagov/govuk_app_config/pull/180 and starts using the latest version ([1.5](https://rubygems.org/gems/statsd-ruby)) of the statsd client, which fixes TCP support.
The statsd client we were using was a temporary replacement for statsd-ruby - see the other PR for details.
> Use statsd-ruby 1.5 client

- CHANGELOG.md
- lib/govuk_app_config/version.rb
This release will allow apps to configure the host and protocol for Statsd.
> Bump gem version to 2.8.2

- CHANGELOG.md
- lib/govuk_app_config/govuk_healthcheck/redis.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_healthcheck/redis_spec.rb
This builds on top of #183 and fixes a potential race condition. See commits for more details.
Thanks to @kevindew for pointing out the issue.
> Redis healthcheck lock

- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_i18n.rb
We have these rules in four different apps so moving them to one place
to make it easier to maintain.
https://trello.com/c/eEphXlio/2394-5-check-and-update-rules-for-plural-forms-across-frontend-apps
> Adds plural rules not available in i18n

- lib/govuk_app_config/govuk_content_security_policy.rb
Adds `lux.speedcurve.com` to the img-src allow list.
Needed for https://github.com/alphagov/static/pull/2445 to work.
This will allow Speedcurve's real user metrics service, called LUX, to load an image beacon that will send real user metrics back to the service.
> Allow LUX domain on img-src policy

- CHANGELOG.md
- lib/govuk_app_config/version.rb
Releases:
* Allow LUX domain on img-src policy #191
> Bump gem verison to 2.10.0

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/govuk_error/configure.rb
- lib/govuk_app_config/version.rb
- spec/govuk_error/configuration_spec.rb
https://trello.com/c/13nqv4jy/2474-3-merge-govukerrors-shouldcapture-method-into-beforesend-🍐
> Merge should_capture into before_send

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/govuk_error/configure.rb
- lib/govuk_app_config/version.rb
- spec/govuk_error/configuration_spec.rb
Follow-on from #196. See commits for details.
Trello: https://trello.com/c/13nqv4jy/2474-3-merge-govukerrors-shouldcapture-method-into-beforesend-%F0%9F%8D%90
> Fix the new `before_send` behaviour & tests, and add documentation

- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_error/govuk_data_sync.rb
- spec/govuk_error/govuk_data_sync_spec.rb
- spec/lib/govuk_content_security_policy_spec.rb
- spec/lib/govuk_healthcheck/checkup_spec.rb
- spec/lib/govuk_logging_spec.rb
- spec/lib/rails_ext/action_dispatch/debug_exceptions_spec.rb
Upgrading rubocop-govuk to version 4 (via running `bundle update` locally) introduces some new rules we need to account for.
We've had to specify a minimum Ruby version, which we have set as 2.6.5 in `.ruby-version`, so I've used that as the basis.
Then it's mostly warnings about declaring classes within tests. Where possible, I've swapped these out for `stub_const`, but we have several tests which rely heavily on the internals of class declaration, inheritence, method overloading and the like, and it seemed less expressive to try to convert these in a way that appeased the linter. I've therefore added some lint-ignore
declarations inline in these files.
> Incorporate latest rubocop rules

- lib/govuk_app_config/govuk_error/configuration.rb
- spec/govuk_error/configuration_spec.rb
In the `before_send` callbacks, the first parameter is of type `Sentry::Event`, and the second parameter (`hint`) is a hash which contains the original exception at key `exception`.
Our datasync-ignorable-exception logic relies on querying the exception chain to see if any of the exceptions in the chain are
of an ignorable exception type. This logic doesn't work when we view the `Sentry::Event` object (as we have been doing) - we must instead look at the `hint[:exception]` object.
The consequence of this bug was that our logic to ignore certain exceptions that occur during the datasync, no longer worked, and we've therefore seen many thousands of Sentry errors since #196 was merged.
However, it wasn't as simple as just checking the `hint` parameter. The `hint` parameter was missing, due …
> Query the original exception rather than Sentry::Event object

- CHANGELOG.md
- README.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_error.rb
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
- spec/govuk_error/configuration_spec.rb
- spec/lib/govuk_error_spec.rb
On 10 December 2020, `sentry-raven` was [deprecated](https://github.com/getsentry/sentry-ruby/tree/master/sentry-raven) and renamed to [`sentry-ruby`](https://github.com/getsentry/sentry-ruby) (which is essentially `sentry-raven` "v4"). `sentry-raven` will [no longer receive any support or bug fixes](https://github.com/getsentry/sentry-ruby/blame/master/sentry-raven/README.md#L18).
The benefits of moving to `sentry-ruby` include:
- Unified interface with other SDKs (i.e. documentation that used to be irrelevant will now be relevant!)
- performance monitoring (though [this isn't included in our plan](https://sentry.io/organizations/govuk/performance/))
- "better extensibility... will allow the community to build extensions for different integrations/features".  (It's not clear what …
> v4 pre-release: upgrade sentry-raven to sentry-ruby

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configure.rb
- lib/govuk_app_config/version.rb
- spec/govuk_error/configure_spec.rb
Attempting to pull govuk_app_config v4.0.0.pre.1 into a project led to a failure, because our default Sentry configuration is
currently invalid. This is now fixed up, and tests added to prevent that happening again.
> Release 4.0.0.pre.2

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_error.rb
- lib/govuk_app_config/version.rb
- spec/lib/rails_ext/action_dispatch/debug_exceptions_spec.rb
In the major release which renamed sentry-raven to sentry-ruby,
the rails config was extracted into its own sentry-rails gem:
https://docs.sentry.io/platforms/ruby/guides/rails/
I had hoped to have downstream apps explicitly
`require "sentry-rails"` only if they need it, however this means
the code is evaluated too late in the process, as GovukError is
already defined at that point. For example, trying to set
`config.rails.report_rescued_exceptions` in email-alert-api on
govuk_app_config v4.0.0.pre.2 leads to this error:
```
NoMethodError: undefined method `rails' for #<GovukError::Configuration:0x000055d424a1a8d0>
```
It seems the only alternative is to include `sentry-rails` in
GovukAppConfig by default. Most of our apps are Rails apps anyway,
so in practice this should DRY up a bit of …
> Release 4.0.0.pre.3

- lib/govuk_app_config/govuk_content_security_policy.rb
Add the domain name that Speedcurve's LUX is using for real user metics - this allows LUX to report on how a page is performing.
> Add Speedcurve's LUX to connect-src policy

- CHANGELOG.md
This release was published from the CLI from commit
968adf5cada7e2435a4b12ab40455907563a25bd.
It contains the code change from
https://github.com/alphagov/govuk_app_config/pull/206
> Add Changelog entry for 3.2.0

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
Smokey has started failing on `cucumber -p staging_aws features/finder_frontend.feature:90 # Scenario Outline: Check search results and analytics`
This is the error:
```
Refused to connect to 'https://hmpowebchat.klick2contact.com/v03/providers/HMPO/api/availability.php' because it violates the following Content Security Policy directive: "connect-src 'self' *.publishing.service.gov.uk *.staging.publishing.service.gov.uk www.gov.uk *.dev.gov.uk www.google-analytics.com ssl.google-analytics.com stats.g.doubleclick.net www.googletagmanager.com www.tax.service.gov.uk hmrc-uk.digital.nuance.com gov.klick2contact.com www.signin.service.gov.uk lux.speedcurve.com".
```
The content security policy originally included `gov.klick2contact.com` in 7c1670bc1dd88955fed54147178e2c661afe2ca7 in January …
> Update reference to klick2contact.com

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
Removes the domain the LUX uses for reporting real user metrics from the `connect-src` content security policy.
Reverts #206.
The domain was originally added because although an image was being used to report the metrics, the image was being served with a content type of `application/javascript`. This meant the loading of the image was being blocked, which prevented any metrics from being reported.
This rule can now be removed from the `connect-src` set of rules as the content type is now `image/webp`:
and is allowed as the domain is in the `img-src` policy:
https://github.com/alphagov/govuk_app_config/blob/a6db8fce8bfaf588053ebb1fe55863043bcc7721/lib/govuk_app_config/govuk_content_security_policy.rb#L36-L38
> Remove Speedcurve's LUX from `connect-src` policy

- CHANGELOG.md
- lib/govuk_app_config/version.rb
Includes:
- Remove Speedcurve's LUX from the connect-src policy ([#216](https://github.com/alphagov/govuk_app_config/pull/216)).
> Release v4.3.0

- CHANGELOG.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_prometheus_exporter.rb
- lib/govuk_app_config/version.rb
- Fix issue where GovukPrometheusExporter module prevented the gem to load due to missing constant. It was unable to find the top level module name "PrometheusExporter" and need to be explicity required.
- Lazy load the prometheus_exporter dependency for only apps that use GovukPrometheusExporter. This prevents the library from being required by apps the don't need it.
- Load GovukPrometheusExporter only for Rails apps, as it loads middleware into Rack and explicitly depends on Rails being present.
> Fix loading gem due missing PrometheusExporter constant

- CHANGELOG.md
- lib/govuk_app_config/govuk_error.rb
Without this non Rails app will get a warning each time they initialise.
For example, Search API has:
```
W, [2022-03-10T09:45:26.609711 #11663] WARN -- sentry: ** [Sentry] sentry-rails can't detect Rails.logger. it may be caused by misplacement of the SDK initialization code
```
> Only require sentry-rails if Rails is defined

- Rakefile
- govuk_app_config.gemspec
It's good to pin this to a particular version of rubocop-govuk,
otherwise we may have different results locally and in CI.
There doesn't seem to be any rationale for the `--format clang` argument
on rubocop so might as well remove it.
> Some rubocop TLC

- CHANGELOG.md
- govuk_app_config.gemspec
We had set up the gem dependencies quite restrictive which meant apps were quite far behind in some cases (Sentry gems are up to 5.2). This updates the gems to their current versions with flexibility for the releases in the current major version. From looking at the respective change logs, both major version updates were very minor and shouldn't require us to make any app changes.
As this project is used as a way to provide dependencies to GOV.UK apps I've taken the approach that this gem pushes for apps to use newer versions rather than be very flexible in what it accepts - this is a deliberate decision to help keep GOV.UK apps on modern versions of dependencies. 
I've put examples of this into a couple of apps with e2e tests to check they pass all tests with these new versions: …
> Loosen and bump dependencies

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
Enable prometheus_exporter on EKS only, extra latency and 500 errors caused on EC2 instances running unicorn, don't expect to see the same on EKS with puma 
([Collections 2712](https://github.com/alphagov/collections/pull/2712))Had to be reverted due to increased latency being seen on the controllers of the collections app running on EC2 instances.
> Add flag to only use prometheus exporter on kubernetes cluster

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
This commit implements the recommended Content Security Policy (CSP) for
SpeedCurve RUM (a.k.a. Lux.js) as per their documentation. We however
have not implemented their script source because we use a self hosted
version of RUM [2].
This adds connect_src as a mechanism to communicate with RUM, this is
needed because the previous method we used to record metrics, LUX.becaonMode,
has been removed from Speedcurve RUM as of version 300 [3] which used
images, whereas version 300 uses JS to send HTTP requests.
I'm not sure if there remains to be any value having an img_src entry
for lux.speedcurve.com as I'm not sure it is used beyond LUX.beaconMode,
however it is still referenced in their recommended CSP [1].
The motivation for making this change is that we are seeing intermittent
errors on …
> Add lux.speedcurve.com to connect_src CSP

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config/govuk_error.rb
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_error_spec.rb
Trello: https://trello.com/c/CXTgjI76/383-look-at-sidekiqjobretryskip-errors-logged-to-sentry
This PR looks to address one of the things that has been problematic since the replacement of sentry-raven, how Sidekiq integrates with Sentry. As part of the introduction [sentry-sidekiq](https://docs.sentry.io/platforms/ruby/guides/sidekiq/) was created as a new gem for integrating with Sentry. In my recent experience of sentry alerts and GOV.UK apps, whether an app alerts to sentry from Sidekiq seems to be rather inconsistent. We're seeing some apps alert Sidekiq::JobRetry::Skip exceptions, others seem to alert nothing - it's a bit confusing but installing sidekiq-sentry seems to settle it down.
I don't think it's a good idea to add sentry-sidekiq as a dependency to this gem however as that …
> Add warnings to integrate GovukError with sentry-sidekiq

- CHANGELOG.md
- lib/govuk_app_config/govuk_error.rb
- lib/govuk_app_config/version.rb
This was accidentally given the wrong name in the warning message.
[sidekiq-sentry does not exist](https://rubygems.org/search?query=sidekiq-sentry) - it should be [sentry-sidekiq](https://rubygems.org/gems/sentry-sidekiq).
> Fix gem name in warning message

- lib/govuk_app_config/govuk_content_security_policy.rb
A new domain has caused our [smoke tests to fail](https://deploy.integration.publishing.service.gov.uk/job/Smokey/40512/console) This adds the new domain in which will hopefully fix the issue
> Add new GA domain to security policy

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
We should update the [Content Security Policy (CSP)](https://github.com/alphagov/govuk_app_config/blob/4c7198b26acdb096be318c7aa343d46f02b7728d/lib/govuk_app_config/govuk_content_security_policy.rb) with `region1.google-analytics.com`.
The current CSP is throwing intermittent errors [on integration](https://www.integration.publishing.service.gov.uk/).
| Before | After |
|---|---|
|<img width="1230" alt="Screenshot 2022-06-20 at 08 45 36" src="https://user-images.githubusercontent.com/44037625/174552010-c6a2e9c5-60ef-47e3-a99a-0691cdeaa36f.png">| |
[Trello](https://trello.com/c/o7LqB0tL/105-update-content-security-policy-csp)
> Add region1.google-analytics.com to CSP

- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_prometheus_exporter.rb
Add Sidekiq Prometheus instrumentation
If Sidekiq is present, add the Sidekiq Prometheus instrumentation.
Ref:
1. [trello card](https://trello.com/c/K8aUtwz4/974-graphs-for-sidekiq-queues-in-grafana)
> Add Sidekiq Prometheus instrumentation

- lib/govuk_app_config/govuk_prometheus_exporter.rb
- lib/govuk_app_config/version.rb
We don't want to initialise the Prometheus exporter when:
- running the Rails console
- running Rake tasks
Otherwise we end up with annoying port clashes and the user has to faff with disabling GOVUK_PROMETHEUS_EXPORTER in the environment just to do something simple like running a rake task or opening a console.
Built and deployed Signon using govuk_app_config from this branch and verified that `rails c` and `/metrics` both work without workarounds.
* Changed signon's `Gemfile`: `gem "govuk_app_config"` -> `gem "govuk_app_config", github: "alphagov/govuk_app_config", branch: "sengi/prometheus-port-clashes"`, run `bundle update govuk_app_config` and pushed those changes to a throwaway branch.
* Built and deployed signon to the integration cluster from the throwaway branch by running the …
> Don't listen on Prometheus metrics port when running interactive.

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
This adds environment names for EKS versions of integration, staging and production.
> Enable EKS environment names for Sentry

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_proxy/static_proxy.rb
- lib/govuk_app_config/railtie.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_proxy/static_proxy_spec.rb
This class can be loaded as Rack middleware and will proxy any requests with the path prefix of `/assets/static` to backend specified. This is useful as it enables Static to use relative paths and the dependent  frontend application can forward those requests. This allows us to switch Static to use relative path and allow us to have development environment and not run Static locally (i.e. forward request to production version of Static).
Rails can be made to initialise the proxy middleware by setting the `GOVUK_PROXY_STATIC_ENABLED=true` env var.
> Add GovukProxy::StaticProxy for development

- CHANGELOG.md
- lib/govuk_app_config/govuk_error.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_error_spec.rb
The Sentry gem spams stdout with INFO logs like this by default, which is particularly annoying when troubleshooting. We don't need info-level logs from the Sentry integration itself.
[Transport] Sending envelope with items [sessions]  to Sentry
This change doesn't affect the logging of events to Sentry, only the logging of messages from the Sentry gem itself. We're therefore only interested in log messages which might indicate that something is wrong, not log messages that simply indicate that something expected is happening - hence WARN is the appropriate level here.
See [Sentry Ruby config docs](https://docs.sentry.io/platforms/ruby/configuration/options/) under `logger`.
> Avoid INFO logspew from the Sentry gem.

- CHANGELOG.md
- lib/govuk_app_config/govuk_error.rb
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
Sentry's default logger turns out to be a reference to `Rails.logger` by default, despite the [sentry-rails docs] saying that it defaults to an instance of `Sentry::Logger`. So I was unwittingly mutating `Rails.logger` through a shared reference. Oops.
Kudos to super sharp-eyed @kevindew for catching this!
Instead of trying to set the log level for the Sentry gem, just disable the "auto session tracking feature" that generates the spammy log messages, since it turns out we don't use that feature. 
Fixes a bug introduced in #263.
[sentry-rails docs]: https://docs.sentry.io/platforms/ruby/guides/rails/configuration/options/
> Fix an ownership bug when configuring the Sentry logger.

- CHANGELOG.md
- lib/govuk_app_config/govuk_i18n.rb
The 7.0.6 release of rails-i18n dropped support for a number of plurals [1] and this causes our apps that make use of these languages to error and thus be unable to update to rails-i18n 7.0.6 (example: https://github.com/alphagov/whitehall/pull/7042)
This commit ports over these rules from rails-i18n to maintain the behaviour.
There is also something of a duplicate of this file in [rails_translation_manager](https://github.com/alphagov/rails_translation_manager/blob/main/config/locales/plurals.rb) that may also need an update. I'm unsure of the status of that file though as it is already out-of-sync with this one and I think this one takes priority.
[1]: https://github.com/svenfuchs/rails-i18n/pull/1017
> Add plurals dropped from rails-i18n in 7.0.6

- CHANGELOG.md
- govuk_app_config.gemspec
- lib/govuk_app_config/railtie.rb
- lib/govuk_app_config/version.rb
This updates this gem to support Plek 5 (with a minor syntax tweak on existing Plek usage) and updates the gem version.
The release also includes: https://github.com/alphagov/govuk_app_config/pull/266
> Update to support Plek 5 and release 4.11.0

- .github/dependabot.yml
Trello: https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions
This makes the dependabot config for this gem consistent with other GOV.UK gems, monitoring bundler and github-actions
> Clean up dependabot

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- spec/lib/govuk_content_security_policy_spec.rb
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
This updates the Content Security Policy in a number of ways:
- It removes legacy declarations: data fonts, various webchat hosts and a verify script
- It simplifies the base CSP rule to be only the current host, whereas previously it was any https script, which seemed rather broad.
- It drops setting a variety of asset hosts, this is no longer needed in production as load all assets with relative paths
- It updates documentation on usage and current intentions.
- It adds https://img.youtube.com as an image-src to support the [YouTube card component](https://github.com/alphagov/govuk_publishing_components/pull/3156)
> Spring clean of the Content Security Policy

- CHANGELOG.md
- lib/govuk_app_config/govuk_logging.rb
- lib/govuk_app_config/version.rb
Log writes to stdout were being buffered such that log entries could be delayed indefinitely, which frustrates troubleshooting in production and can lead to log messages being lost on crash.
Explicitly enable [IO.sync] on stdout/stderr to have Ruby flush writes immediately to the underlying system.
stderr was actually already unbuffered, but since we need to set stdout I think it'd be confusing not to specify both.
While we're there, remove a couple of redundant comments and tidy up the remaining ones.
[IO.sync]: https://ruby-doc.org/2.7.7/IO.html#method-i-sync-3D                               
```
ruby <<'EOF'
puts "$stdout.sync=#{$stdout.sync}"
puts "$stderr.sync=#{$stderr.sync}"
puts
$real_stdout = $stdout.clone
$stdout.reopen($stderr)
puts "$stdout.sync=#{$stdout.sync}"
puts …
```
> Flush log writes to stdout immediately.

- CHANGELOG.md
We were all in on asterisks until version 3.1 and then went with dashes.
> Fix inconsistent bullets in changelog

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
This applies a number of changes to the Content Security Policy provided by this gem. It:
- removes unsafe_inline from script-src ~and style-src~, which means that any usages of `<script>` ~or `<style>`~ elements requires a nonce ~and usage of inline styles are forbidden~. This is to limit the damage an attacker can do with ability to inject HTML into a page. (Note: I wasn't able to disable unsafe-inline on style due to [Govspeak](https://github.com/alphagov/govspeak/blob/5642fcc4231f215d1c58ad7feb30ca42fb8cfb91/lib/govspeak/html_sanitizer.rb#L72-L73) usage) 
- removes ability to embed images with `data:` URLs. This limits any injected HTML to not display arbitrary images
- disallows a …
> Configure Content Security Policy to remove risky allowed properties

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
- lib/govuk_app_config/version.rb
At present, [we include this module](https://github.com/alphagov/search-api/blob/1b881b0ff1f2c6d65bc02d30b1f323ccd0633029/config/initializers/prometheus.rb#L2) but it doesn't seem to get plumbed into middleware.
This affects search-api and bouncer.
When I deployed a branch of search-api to integration referencing this branch, metrics appeared almost immediately
> Release v6.0.0 and add Prometheus support for Sinatra

- CHANGELOG.md
- lib/govuk_app_config/govuk_puma.rb
This will allow us to set a different timeout for production systems. The need for this arose because of timing out requests for HMRC manuals api, which we [allowed for configuration of](https://github.com/alphagov/govuk_app_config/blob/c68fb5816906bde162d95e8c2738cde9f8f1d1d1/lib/govuk_app_config/govuk_unicorn.rb#L5) when it was unicorn- rather than puma-based.
I'll release this in a follow-up PR.
[Trello](https://trello.com/c/qtpjC3PB/556-increase-timeout-for-hmrc-manuals-api)
> Allow puma timeout to be configurable

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
- spec/govuk_error/configuration_spec.rb
`active_sentry_environments` was a hard-coded list of allowable values for the Sentry `environment` tag. It was [introduced](https://www.github.com/alphagov/govuk_app_config/pull/168) during the Replatforming discovery phase in 2020 in order to prevent the Puppet/EC2 stack in the test account from sending events to Sentry.
(It was done this way because at that time, disabling Sentry in the test environment was more difficult than it should have been, while some teams had Sentry alerts and Slack subscriptions which didn't select by environment).
We don't need this feature any more and we're now better off without it, because it complicated the semantics of `SENTRY_CURRENT_ENV` in a way that is surprising to the user.
This fixes a current problem where apps in the integration cluster are …
> 7.1.0: Remove hardcoded allowlist of Sentry environment names.

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
Add HttpParserError to excluded exceptions
Sentry ruby 5.9 ensured that low level puma errors were captured and propagated to sentry. This ended up in a lot of noise [1] in sentry when applications were bumped to this version of sentry ruby, particularly with Puma::HttpParser errors.
These errors are often unactionable and we believe a result of crawler activity. This suppresses these errors in order to reduce sentry noise.
1: https://govuk.sentry.io/issues/4154286086/?project=202217
> Add Puma::HttpParserError to excluded exceptions

- lib/govuk_app_config/govuk_prometheus_exporter.rb
- This allows us to (eg) run rake tasks or db migrations in situations where the port is already bound (for instance in a pod shell)
> Allow prometheus binding to fail with a warning rather than a crash

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
This continues the work from https://github.com/alphagov/govuk_app_config/pull/279 to remove risky properties from our Content Security Policy (CSP) by removing unsafe-inline from style properties.
We have been able to resolve the need for this property by updating Govspeak [1].
I've marked this as a breaking change as it forbids something fundamental, however this is really quite a soft breaking change as a) there has been lots of prep work across GOV.UK to prepare for it and b) the CSP is in report only mode across GOV.UK so won't actually block any usages.
~Prior to merging this we need to represent any content that uses tables with text alignment to the Publishing API to remove their inline styles. I've opened this as a draft while this is completed.~
Edit: 2 June, I've been through …
> Forbid unsafe-inline for style attributes in CSP

- CHANGELOG.md
- lib/govuk_app_config/govuk_logging.rb
- lib/govuk_app_config/version.rb
The logstash gem adds a field to logs called "source" and by defaults sets it a string representing the host IP address. Our Elasticsearch mapping expect source to be of type object, to support subfield such as source.ip or source.address etc. This causes Elasticsearch to drop the logs resulting in missing Rails logs.
There's currently no way to rename the field (as the field is added after the logstasher's renaming config) and it cannot be disabled. This field is of limited use as the value is usually just the K8s pod IP address.
> Fix dropped logs due to incorrect source field type

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
- lib/govuk_app_config/version.rb
The workers were erroring with:
```
PrometheusExporter::Instrumentation::SidekiqProcess Prometheus Exporter Failed
To Collect Stats uninitialized constant Sidekiq::Process
PrometheusExporter::Instrumentation::SidekiqQueue Prometheus Exporter Failed To
Collect Stats uninitialized constant Sidekiq::Queue
PrometheusExporter::Instrumentation::SidekiqStats Prometheus Exporter Failed To
Collect Stats uninitialized constant Sidekiq::Stats
```
and failing to send metrics following a switch from Statsd to Prometheus Exporter: https://github.com/alphagov/govuk_sidekiq/commit/763144dd055ab286a020902e7d63a21eec428155
Sidekiq::Process, Sidekiq::Queue, Sidekiq::Stats are defined in Sidekiq API. It appears that to get access to the functionality, the API needs to be required. See …
> Require sidekiq/api in GovukPrometheusExporter

- CHANGELOG.md
- README.md
- govuk_app_config.gemspec
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_open_telemetry.rb
- lib/govuk_app_config/railtie.rb
- lib/govuk_app_config/version.rb
This adds the ability to enable Open Telemetry instrumentation in Rails by setting the "ENABLE_OPEN_TELEMETRY" environment variable to "true".
The service name is automatic set to the Rails application name.
---
This is work done part as GIFT week and should initially only be enabled in integration. Should be removed if ultimately not implemented/used.
> Add support Open Telemetry instrumentation in Rails

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
- lib/govuk_app_config/version.rb
This switches prometheus_exporter's method patching to use `prepend` instead of `alias_method`. Prepend is negligibly slower than alias_method, but is more compatible other libraries.
https://github.com/discourse/prometheus_exporter#choosing-the-style-of-method-patching
https://samsaffron.com/archive/2017/10/18/fastest-way-to-profile-a-method-in-ruby#fastest-way-to-patch-a-method-3
The issues with alias method cause a recursive call between prometheus_exporter and open telemetry sdk when making calls to SQL and redis.
> Fix prometheus_exporter to method patching compatible with open telemetry

- CHANGELOG.md
- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_json_logging.rb
- lib/govuk_app_config/rails_ext/action_dispatch/debug_exceptions.rb
- lib/govuk_app_config/railtie.rb
- spec/lib/govuk_json_logging_spec.rb
- spec/lib/rails_ext/action_dispatch/debug_exceptions_spec.rb
This is to allow setting production-like behaviour by using the `ENABLE_PRODUCTION_LIKE_LOGS` env variable. This will be set in `govuk-heml-charts` -> `env-configmap.yaml`. The purpose is to allow developers to override this env var in order to test changes to production logs locally.
[Trello card](https://trello.com/c/niLCNflj/117-story-enable-production-like-logging-in-dev-environments)
> Enable production-like logs if env variable is set

- CHANGELOG.md
- lib/govuk_app_config/govuk_json_logging.rb
- lib/govuk_app_config/version.rb
Kibana validates log lines by index patterns and "error" is supposed to be an object. Since error is a string in logstaher's world we are renaming it to "message" which will be accepted as string.
> Fix dropped logs due to incorrect error field type

- CHANGELOG.md
- lib/govuk_app_config/railtie.rb
- lib/govuk_app_config/version.rb
This fixes a bunch of annoying warnings on startup, avoids generating traces from interactive use by default, and possibly reduces the chance of OOM when execing `rails console` inside a serving app container.
(Thought about putting the condition in `GovukOpenTelemetry::should_configure?` but given that the condition is specific to the Rails use case, the Railtie seemed like the better/cleaner place to put it.)
> Don't init OpenTelemetry when in `rails console`.

- CHANGELOG.md
- lib/govuk_app_config/govuk_json_logging.rb
- lib/govuk_app_config/version.rb
Rails libraries expect the `Rails.logger` instance to inherit from ActiveSupport::Logger. The ruby standard library logger for example does not implement methods like `silence` which is used by some of the Rails internals. 
This change fixes the inheritance issue.
Co-authored-by: laura.ghiorghisor@digital.cabinet-office.gov.uk
This fixes the below error:
The error appears in development environment when Production like logging is enabled.
Tested with happy results:
> Use ActiveSupport::Logger instead of Ruby std Logger for the Rails apps

- CHANGELOG.md
- lib/govuk_app_config/govuk_open_telemetry.rb
https://github.com/alphagov/govuk_app_config/pull/307 removes OpenTelemetry initialisation in the console to avoid flooding the console with OpenTelemetry startup messages.
This PR adds the additional behaviour that when OpenTelemetry _is_ configured (ie we are not on a console), we do a second check to see whether we're in a rake task and silence OpenTelemetry log messages so that Rake tasks with simple text output are not swamped with OpenTelemetry startup messages.
Since we're already assuming Rails.const_defined? is available, we use it to check for Rake, then call Rake.application.top_level tasks, which returns an empty array if running in rails, but a list of tasks if running through rake.
> GovukAppConfig silences OpenTelemetry log output when running a rake task

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
This makes the warning message less confusing, as error is about the Prometheus metrics server failing to start rather than being unable to connect to Prometheus itself.
> Update warning about address in use for Prometheus metrics server

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
This extends application Prometheus exporter configuration to load custom collectors. This is required by application that would like to support global metrics (e.g. user/article counts). Specifically this is need to support Signon provide metrics for token expiry timestamps.
Following the global metrics pattern outlined in the [prometheus_exporter docs](https://github.com/discourse/prometheus_exporter#global-metrics-in-a-custom-type-collector).
> Add ability to specify custom collectors

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
Prometheus histograms / summaries are complex and hard to wrap one's head around. The difference between them is also quite subtle and confusing to the uninitiated.  I'm sure I won't do a good job of explaining the difference in this commit message, so I'll just link to the docs[0].
The key difference for us is that summaries can't be aggregates, but histograms can.
For example, if I'm looking at http_request_duration_seconds, we might want to know "what's the 95%ile request time for this controller action". We can answer this question for a particular application instance (i.e. a specific pod) with both histograms and summaries. If we want to know the 95%ile request time aggregated across all instances / pods however, we can only do that with histograms. This is because in summaries, …
> Default to Prometheus histograms, not summaries

- lib/govuk_app_config/govuk_prometheus_exporter.rb
I've got an open PR to do this for the default default in prometheus_exporter itself:
`discourse/prometheus_exporter/pull/293`
But it's unclear whether the maintainers will accept that, and if so how long that will take.
In the meantime, we've got quite a bit of noise in our metrics because it's currently possible for an HTTP request to overwrite the action / controller labels by passing them in as request parameters like this:
curl -v http://127.0.0.1:3000/ --data 'controller=test'
This commit extends the default middleware so we have more sensible defaults for both Rails and Sinatra apps. I couldn't work out any good labels for sinatra apps that wouldn't be potentially high cardinality, so those are just blank.
> Get controller labels from controller, not params

- lib/govuk_app_config/govuk_content_security_policy.rb
Other sites could iframe GOV.UK into theirs and potentially use CSS/JS clickjacking to capture keystrokes etc.  It was not done before because in 2020 there were a couple of instances where non-origin framing was a valid use case (e.g. we used to a side-by-side browser for sites transitioning content to GOV.UK so the departments could see where their pages will redirect to)
In 2023, the [side-by-side browser](https://docs.publishing.service.gov.uk/repos/side-by-side-browser.html) is now retired, and we now have the GOV.UK Account in place and a potential move towards personalisation, so the likelihood of an attacker attempting to steal GOV.UK credentials is growing.
[Trello card](https://trello.com/c/QC9k1z4a/3303-prevent-iframing-of-govuk-3)
Disallow any domain from embeding a page to …
> Disallow any domain from embeding a page to prevent clickjacking

- spec/lib/govuk_content_security_policy_spec.rb
The test started failing because Rails now prevents meaningless assignments to a configuration key by raising NoMethodError.  See: https://github.com/rails/rails/commit/265bfad5fb7f875dfb3ddfafd895cb2ec80458f7
```
GovukContentSecurityPolicy.configure creates a policy
Failure/Error: Rails.application.config.content_security_policy = nil
NoMethodError:
Cannot assign to `content_security_policy`, it is a configuration method
raise NoMethodError.new("Cannot assign to `#{key}`, it is a configuration method")
^^^^^
```
> Fix GovukContentSecurityPolicy test

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
It was not added initially to the global Content Security Policy as it was not needed for YouTube thumbnails on image cards, however is used for videos themselves within publications body.
For example:
https://www.gov.uk/government/publications/car-show-me-tell-me-vehicle-safety-questions/car-show-me-tell-me-vehicle-safety-questions
> Allow YouTube thumbnails from https://i.ytimg.com

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_json_logging.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_json_logging_spec.rb
I.e. allow apps to add their own custom fields in addition to those that
`GovukJsonLogging` already adds.
It looks like `LogStasher.add_custom_fields` can only be called one
time, otherwise subsequent calls overwrite previous ones.
We found this [happening in the wild in the Content Store app](https://github.com/alphagov/content-store/blob/v33/config/initializers/logstasher.rb#L2), where
`govuk_request_id` et al were missing from the Rails framework logs but
present whenever the logger had been invoked directly from our own code.
This approach does solve the problem for Content Store (along with a
change to Content Store to actually use this option), but I'm keen to hear
suggestions of alternatives.
(https://trello.com/c/jDSDGNyn/814-measure-and-record-our-publishing-latency-sli)
> Enable adding custom LogStasher fields from apps

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
The `assets.publishing.service.gov.uk` domain can't POST to the feedback form without this, so users can't report problems with our CSV preview pages.
> Add GOVUK domains to script src CSP

- CHANGELOG.md
- lib/govuk_app_config/govuk_content_security_policy.rb
- lib/govuk_app_config/version.rb
This reverts commit b30410cbfd7c72cec77e6580e13147ed55d535be.
We thought it would solve a CORS issue, but it did not so we don't need this change.
> Revert "Add GOVUK domains to script src CSP"

- .rubocop.yml
- README.md
- lib/govuk_app_config/govuk_error/configuration.rb
- spec/govuk_error/configuration_spec.rb
Fixes #341
`SimpleDelegator` was intercepting the `lambda` call via `method_missing`, and delegating to `Kernel#lambda`, passing the given block. This explodes on Ruby 3.3 because `lambda` only accepts block literals now.
Replacing the `lambda` call with this shorthand syntax sidesteps the issue. RuboCop is unhappy because it prefers the old syntax for multiline lambdas, so I've had to disable that cop.
Tested locally against Content Data Admin.
> Use shorthand lambda syntax

- CHANGELOG.md
- lib/govuk_app_config/version.rb
Dropping support for a Ruby version should be a minor bump according to https://docs.publishing.service.gov.uk/manual/publishing-a-ruby-gem.html#ruby-version-compatibility
> Bump gem version

- lib/govuk_app_config/govuk_content_security_policy.rb
Adds the URLs for the single cookie consent API into the CSP. Once the single consent API is enabled on GOV.UK the JS will be making XMLHttprequests to the staging and production environments for the single consent api, so these URLs need to be added to the CSP.
Trello card: https://trello.com/c/dmlTAzKB/140-implement-single-consent-api
> Add single cookie consent api URLs

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
Some client apps have started to assume that the Prometheus "exporter" process (i.e. the process that aggregates counters in multi-process apps) is always available, including in tests.
Now that we handle the case where the `/metrics` port is already taken, there's really no reason not to initialise GovukPrometheusExporter.
Remove the confusing heuristics in `GovukPrometheusExporter.should_configure` and just always attempt to initialise unless we're running under `rails console`. When the init fails, we just print a warning and continue anyway, so this should be a net win for robustness.
If we find edge cases where this still needs to be configurable then I propose we address those if/when we find and understand them. I expect we won't need to, though.
Kudos to @leenagupte for reporting …
> 9.10.0: Always initialise GovukPrometheusExporter.

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
Related to: https://github.com/alphagov/gds-sso/pull/300
-  We do not need to capture these errors generated from gds-sso. They do not indicate that something went wrong with the application; rather, they indicate that a user does not have permissions to access a resource.
trello card: https://trello.com/c/qb1qpwnr/1369-additional-functionality-to-gds-sso-gem-for-intercepting-401s-and-providing-a-route-constraint
> Add GDS::SSO::PermissionDeniedError to excluded exceptions list

- CHANGELOG.md
- lib/govuk_app_config/govuk_json_logging.rb
- lib/govuk_app_config/govuk_json_logging/rails_ext/action_controller/metal/instrumentation.rb
- spec/lib/govuk_json_logging_spec.rb
The logstasher gem monkey patches the `process_action.action_controller` instrumentation. However the gem hasn't been updated for Rails 7, which assumes that the payload has the 'request' object available. This request object is used by the OpenTelemetry SDK to process spans. This generates lots of error logs from the SDK, and prevents us from recording some spans.
This re-monkey patches the instrumentation to use a raw_payload that is expected in Rails 7.  Ideally, this would be fixed in the logstasher gem however there has been little active development over the last year. Longer term fix might be to move to a maintained logging library.
> Fix OpenTelemetry span processing when using logstasher

- CHANGELOG.md
- lib/govuk_app_config/govuk_json_logging.rb
- lib/govuk_app_config/version.rb
For some apps the initialisation order means that the logstasher is initialiser after and therefore the original patch is applied after the patch from this library, effectively disabling the fix for [OpenTelementry traces](https://github.com/alphagov/govuk_app_config/pull/372).
This sets the config option to prevent the logstasher from applying its patch after, if the original patch is already applied.
> Prevent old logstasher monkey patch from overriding patch

- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_timezone.rb
- lib/govuk_app_config/railtie.rb
- spec/lib/govuk_timezone_spec.rb
Our conventions for rails apps say that we should set time_zone to London:
https://docs.publishing.service.gov.uk/manual/conventions-for-rails-applications.html#specify-london-as-the-timezone
In practice however, only about half of the apps do so. Based on the apps running in integration:
Apps which set the time_zone to London:
AccountApi
Collections
CollectionsPublisher
ContentPublisher
Collections
Frontend
GovernmentFrontend
Static
EmailAlertApi
Frontend
GovernmentFrontend
GovukChat
LocationsApi
Maslow
PlacesManager
Publisher
ReleaseApp
SearchApiV2
Signon
SmartAnswers
SpecialistPublisher
Static
Whitehall
Apps which leave the time_zone as it's default UTC:
AuthenticatingProxy
Contacts
ContentDataAdmin
ContentPerformanceManager
ContentStore
ContentTagger
ContentStore
RouterApi …
> Set time_zone to London in all GOV.UK apps

- CHANGELOG.md
- lib/govuk_app_config/version.rb
I've made this a minor version, even though it's technically a breaking change (or at least, updating will result in a change in behaviour).
I'm pretty confident that the new behaviour (London time_zone instead of UTC) is correct for all GOV.UK apps, so they shouldn't need to think about this as a "breaking" change.
> Cut release for London Time zone

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
⚠️ Make sure you [release a new version of this gem](https://github.com/alphagov/govuk_app_config/pull/356/files) after merging your changes. ⚠️
Refer to the [existing docs](https://docs.publishing.service.gov.uk/manual/publishing-a-ruby-gem.html#ruby-version-compatibility) if you are making changes to the supported Ruby versions.
We keep getting the following exception in production: https://govuk.sentry.io/issues/4958108827/?environment=production&environment=production-eks&environment=producton&project=-1&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=9
After [the discussion](https://gds.slack.com/archives/C052X8S2P8A/p1718796354165479) there was a suggestion to keep the SourceWrapperNotFoundError instead of reverting the PRs introducing it. The error should …
> Exclude Slimmer::SourceWrapperNotFoundError

- lib/govuk_app_config/version.rb
The auto-release workflow is not working as expected https://github.com/alphagov/govuk_app_config/pull/386/files
---
⚠️ Make sure you [release a new version of this gem](https://github.com/alphagov/govuk_app_config/pull/356/files) after merging your changes. ⚠️
Refer to the [existing docs](https://docs.publishing.service.gov.uk/manual/publishing-a-ruby-gem.html#ruby-version-compatibility) if you are making changes to the supported Ruby versions.
> Really release v9.13.1

- CHANGELOG.md
- README.md
- lib/govuk_app_config/govuk_timezone.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_timezone_spec.rb
In the original implementation of the GovukTimezone module we assumed that literally all GOV.UK apps would use the London timezone. We didn't really consider how to make it easy for apps to override this if needed.
Since then, we've found a couple of examples where apps genuinely do want to override the timezone:
- publishing-api, which always wants to present dates as UTC because its an API
- travel-advice-publisher, which always wants to present dates as UTC because a majority of its users are in non-London timezones (so BST is confusing)
Currently, these apps override GovukTimezone by inserting an initializer between it and active_support.initialize_time_zone like this:
initializer "publishing_api.configure_timezone",
after: "govuk_app_config.configure_timezone",
before: …
> Configure time_zone with govuk_time_zone

- CHANGELOG.md
- lib/govuk_app_config/govuk_healthcheck/sidekiq_redis.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_healthcheck/sidekiq_redis_spec.rb
This healthcheck has been failing for applications that have upgraded to Sidekiq 7. Sidekiq 7 uses `redis-client`' which has a different API to `redis` which was used in Sidekiq 6.
To access `redis_info` you now have to call
```
Sidekiq.default_configration.redis_info
```
while in Sidekiq 6 you call
```
Sidekiq.redis_info
```
This updates the healthcheck to work with both versions of Sidekiq checking if`Sidekiq responds to `.redis_info`.
If it does it calls that, otherwise it calls `Sidekiq.default_configration.redis_info`.
It's not massively clear these healthchecks are actually being used for anything since this has been failing on production applications for a couple of weeks without anyone noticing.
We're in the process of speaking to the platform team to see if they're actually being …
> Update SidekiqRedis healthcheck to work with Sidekiq 7

- CHANGELOG.md
- lib/govuk_app_config/govuk_error/configuration.rb
- lib/govuk_app_config/version.rb
⚠️ Make sure you [release a new version of this gem](https://github.com/alphagov/govuk_app_config/pull/356/files) after merging your changes. ⚠️
Refer to the [existing docs](https://docs.publishing.service.gov.uk/manual/publishing-a-ruby-gem.html#ruby-version-compatibility) if you are making changes to the supported Ruby versions.
Do not send Sanitiser::Strategy::SanitisingError to Sentry. This error should still be raised in all environments.
This error is raised in some apps when an incorrect (wrong UTF-8 encoding) character is encountered in a query string or in a cookie.
[Trello card](https://trello.com/c/FeOwxE2x/2938-silently-handle-invalid-byte-sequence-in-utf-8-errors-l)
> Add Sanitiser::Strategy::SanitisingError to the list of excluded errors

- CHANGELOG.md
- lib/govuk_app_config/govuk_prometheus_exporter.rb
- lib/govuk_app_config/version.rb
Apps can use request.env['govuk.prometheus_labels'] to specify custom labels for prometheus.
For example, and app might do:
prometheus_labels = request.env.fetch('govuk.prometheus_labels', {})
request.env['govuk.prometheus_labels'] = prometheus_labels.merge(
document_type: @content_item.document_type,
schema_name: @content_item.schema_name,
)
To set the document type / schema name as custom labels (which is useful for the apps where this isn't obvious based on controller / action, like government-frontend)
Testing locally, this results in metrics like:
http_request_duration_seconds_count{action="show",controller="content_items",document_type="answer",schema_name="answer"} 1
Care does need to be taken with the cardinality of prometheus labels (i.e. there shouldn't be too many different …
> GovukPrometheus - custom labels from rack env

- CHANGELOG.md
- README.md
- lib/govuk_app_config.rb
- lib/govuk_app_config/govuk_i18n.rb
- lib/govuk_app_config/govuk_i18n/docs/example.yml
- lib/govuk_app_config/version.rb
- spec/lib/govuk_i18n_spec.rb
Some languages that are supported by GOV.UK are not yet supported by the
Rails framework. (See [audit](https://docs.google.com/spreadsheets/d/1zbpROLIsFz2ef7JYT8qUlptV7Blp1O0aEENj7CM2HJ8/edit?usp=sharing))
This module allows us to patch these translations so that things like days of the week, month names etc are populated. 
|Before|After|
|-|-|
|<img width="414" alt="Screenshot 2025-04-03 at 13 08 48" src="https://github.com/user-attachments/assets/acb93afe-fa9f-43a6-a29c-ba8dc4137d25" />|<img width="450" alt="Screenshot 2025-04-03 at 13 20 47" src="https://github.com/user-attachments/assets/bb46a8a4-1798-4599-bd20-79c9f8d09b30" />|
[Trello](https://trello.com/c/pJYPgL2D/3396-prepare-prs-to-import-rails-translations)
See review app at https://github.com/alphagov/frontend/pull/4743 which …
> Add support for internationalisation of Rails framework strings

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/govuk_app_config/version.rb
**As a** platform engineer
**I want** our deployment process for our app repos to handle concurrent releases
**so that** we avoid issues with incorrect ordering of releases
https://github.com/alphagov/govuk-infrastructure/issues/2123
> Configure CI workflow to handle concurrent releases

- CHANGELOG.md
- docs/healthchecks.md
- lib/govuk_app_config/govuk_healthcheck.rb
- lib/govuk_app_config/govuk_healthcheck/emergency_banner_redis.rb
- lib/govuk_app_config/version.rb
- spec/lib/govuk_healthcheck/emergency_banner_redis_spec.rb
Apps that stop relying on static need to reach into the emergency banner redis to check if there's a banner that should be displayed, but we don't have a health check for that config/connectivity, and it's already common across than more than one app.
Static itself is a good example, if the emergency banner redis isn't available static returns errors. I need to add a check of that emergency banner redis connectivity to the startupProbes for static, so it seemed sensible to make this a reusable healthcheck rather than solely implementing it in static.
When I update static to use this, I will also update it's docs to instruct that this healthcheck should be added to apps which remove their static dependency
⚠️ Make sure you [release a new version of this …
> Release v9.19.0: Add an EmergencyBannerRedis health check
